[tool.hatch.envs.default]
dependencies = [
  "copier",
  "uv",
  "mystmd"
]
scripts.copy = [
  "copier copy --vcs-ref=HEAD . {args:.tmp/py-package}",
]
scripts.install = [
  "copier copy --vcs-ref=HEAD . .tmp/py-package -f",
  "uv pip install .tmp/py-package",
]
scripts.check = [
  "copier copy --vcs-ref=HEAD . .tmp/py-package -f",
  "cd .tmp/py-package && hatch run precommit:run -av",
]
scripts.clean = [
  "ruff clean",
  "rm -rf .tmp",
]

[tool.hatch.envs.docs]
detached = true
dependencies = [
  "mkdocs",
  "mkdocs-material"
]
scripts.build = "mkdocs build --clean --strict"
scripts.serve = "mkdocs serve --dev-addr localhost:8000"
scripts.deploy = "mkdocs gh-deploy --force"
